sudo: required
services:
  - docker

before_install:
  - docker build -t jackydevacc/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jackydevacc/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "frontend"
  env: "Frontend-env"
  bucket_name: "elasticbeanstalk-us-east-2-247734093061"
  bucket_path: "frontend"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  